# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yifan Guan
email: yfguan@umich.com
description: >- # this means to ignore newlines until "baseurl:"
  Copyright: 2020 Yifan Guan
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://yifanguan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
version: 1.0.0

# third-party accounts
github_username: yifanguan
disqus:
    shortname: yifanguan

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

global_css: '/static/website.css'
avatar: '/static/avatar_2.jpg'
cv: '/resources/cv.html'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
